version: "3"
services:

  mangrove:
    container_name: mangrove-server
    build: .
    environment:
      - DOCKER_MANGROVE=yes
    command:
      - $CMD
    volumes:
      - $MANGROVE_INPUT_DIR:/inputs
      - ../:/mangrove
    ports:
      - "34251:34251"
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: mangrove-server-mongodb
    image: mongo
    volumes:
      - $MANGROVE_HOME/db:/data/db
    ports:
      - "34252:27017"

  redis:
    container_name: mangrove-server-redis
    image: redis
    ports:
      - "34253:6379"
